### PR TITLE
keyboard controller tested and functioning

### PR DESCRIPTION
**Pull request by sethherr**
A larger pull request, and contains a few things, but was intended to be modular - there are the things I used to get a tested and functional keyboard controller.

- added `slug` to Layout to successfully find and associate keyboards with layouts
- added activemodel serializers and the required serializer files to return the JSON in the format you're using right now
- added `update` and `create` actions to the keyboard controller, and tests for them.

### CODE REVIEW

**Comment by sethherr** [comment]
Right now, if you go to the new keyboard page, and save a layout, it will save - but every time that you save it will create a new layout.

**Comment by sethherr** [comment]
After getting back the save, we should use the ID that is returned to set up the correct url.

**Comment by sethherr** [comment]
Updates the ajax url and method on a success response, so that if a new keyboard is created, it updates that keyboard instead of just creating other new keyboards.

**Comment by tdegrunt** [comment]
Awesome!

**Pull request merged**
