### PR TITLE
Create a cannonical place for keycode generation

### PR DESCRIPTION
**Pull request by sethherr**
Because #10 and #19 will both require adding more information to the keys, it makes sense to put the key information in a single place, that's easier to browse and that is easier to update. Since github renders csvs, it's a great way of representing spreadsheet data and giving everyone a way to edit it.

This includes the ruby necessary to generate a hash from the csv, and it rewrites the existing keycodes.js file to be generated by the ruby method, instead of an incomprehensible (and difficult to edit) list of arrays.

The more accessible something like this is to editing, the more likely people will update it.

### CODE REVIEW

**Comment by tdegrunt** [comment]
Not so sure about this, it just adds another layer of abstraction. 

What's wrong with a JSON hash, this just seems to make it more complicated, while keeping the keycodes.js (though it's generated).

Anyone contributing would need to be able to do JS, Ruby, etc anyway

**Comment by sethherr** [comment]
Not true. You can edit the csv on github.com, https://github.com/sethherr/fusion/blob/keymap_generation/lib/key_map/key_map.csv

Or you can download the file in excel and alter it. You definitely don't need to know ruby or js to be able to help with the presentation of keys.

**Comment by tdegrunt** [comment]
Anyone contributing to the repository would need to know ruby/js. 

I'd rather see this in the JS than in a CSV, which in turn using a bunch of Ruby to generate a JS file. 
It seems better to improve the format of the JS.

**Comment by sethherr** [comment]
I'm not sure why someone contributing to this repository would need to know ruby or js. As I just showed you in the link, you can view the spreadsheet of the keycodes on github.com, and then you can click the little edit button and edit it. No ruby or js or programming knowledge required. Which is convenient for presentation things like this, because oftentimes, the people who are most concerned about presentation are the ones who have the least programming skill.

That table is way, way easier to look at than js for me. I can't scan through JSON and see everything (particularly with symbols encoded) and how it works together. When we add another key (e.g. #27), I'll open this in libre office, add an extra column, and fill in the values. Maybe you have mad json vision skills, but I don't.

Seriously. Just open https://github.com/sethherr/fusion/blob/keymap_generation/lib/key_map/key_map.csv

When this pull request is merged in, that will be linked in the readme. Doesn't that look way nicer to you?

Also it's tested right now in ruby, which is a big improvement over it being untested in js.

**Comment by sethherr** [comment]
What this is about is creating a canonical list of the keyboard codes. Right now that list is stored as a comment in a C file, which is inaccessible and intimidatingly unupdatable.

This creates a way for everyone to see the key codes and update them.

Right now there isn't a next media symbol, for example. I'm not going to add that. You clearly haven't added that either. That's something that someone else can add easily. And if, when they start editing their keyboard layout, they're given a link to the spreadsheet on github, they will.

**Comment by ezuk** [comment]
I must say I agree with Tom on this one. Here's the gist of it imho: The keycodes work, or don't work, based on what's in `qmk`. _That_ should be our canonical source for the keycodes available, because that's the simple truth -- if it isn't implemented in `qmk`, it's not gonna work for us.

I feel that by creating another "canonical" keycode source, we are masking this simple fact, and setting ourselves up for all sorts of conflicts and confusions. Non-technical people (for whom a C file is too intimidating, even if formatted for readability) are bound to try and add new keycodes here, thinking that just adding them to the CSV is going to be enough to make the magic happen.

So, I gotta say my vote goes against this particular PR. Just my two cents. I'd rather invest in readability of the source code, and more important, I'd much rather have a working, deployed MVP, even if limited to a particular subset of keys -- with expandability coming in later.

**Pull request closed without merging**
